# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dirk/Documents/Code/qt/Komics/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnArchivePrevious = QtWidgets.QPushButton(self.centralWidget)
        self.btnArchivePrevious.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/skip-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnArchivePrevious.setIcon(icon)
        self.btnArchivePrevious.setIconSize(QtCore.QSize(24, 24))
        self.btnArchivePrevious.setObjectName("btnArchivePrevious")
        self.horizontalLayout_4.addWidget(self.btnArchivePrevious)
        self.btnArchiveBeggining = QtWidgets.QPushButton(self.centralWidget)
        self.btnArchiveBeggining.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnArchiveBeggining.setIcon(icon1)
        self.btnArchiveBeggining.setIconSize(QtCore.QSize(24, 24))
        self.btnArchiveBeggining.setObjectName("btnArchiveBeggining")
        self.horizontalLayout_4.addWidget(self.btnArchiveBeggining)
        self.btnPageBack = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageBack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/step-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPageBack.setIcon(icon2)
        self.btnPageBack.setIconSize(QtCore.QSize(24, 24))
        self.btnPageBack.setObjectName("btnPageBack")
        self.horizontalLayout_4.addWidget(self.btnPageBack)
        self.btnPageGoTo = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageGoTo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPageGoTo.setIcon(icon3)
        self.btnPageGoTo.setIconSize(QtCore.QSize(24, 24))
        self.btnPageGoTo.setObjectName("btnPageGoTo")
        self.horizontalLayout_4.addWidget(self.btnPageGoTo)
        self.btnPageForward = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageForward.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/step-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPageForward.setIcon(icon4)
        self.btnPageForward.setIconSize(QtCore.QSize(24, 24))
        self.btnPageForward.setObjectName("btnPageForward")
        self.horizontalLayout_4.addWidget(self.btnPageForward)
        self.btnArchiveEnd = QtWidgets.QPushButton(self.centralWidget)
        self.btnArchiveEnd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnArchiveEnd.setIcon(icon5)
        self.btnArchiveEnd.setIconSize(QtCore.QSize(24, 24))
        self.btnArchiveEnd.setObjectName("btnArchiveEnd")
        self.horizontalLayout_4.addWidget(self.btnArchiveEnd)
        self.btnArchiveNext = QtWidgets.QPushButton(self.centralWidget)
        self.btnArchiveNext.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/assets/icons/36/skip-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnArchiveNext.setIcon(icon6)
        self.btnArchiveNext.setIconSize(QtCore.QSize(24, 24))
        self.btnArchiveNext.setObjectName("btnArchiveNext")
        self.horizontalLayout_4.addWidget(self.btnArchiveNext)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnViewWidthFit = QtWidgets.QPushButton(self.centralWidget)
        self.btnViewWidthFit.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/icons/36/window_width.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViewWidthFit.setIcon(icon7)
        self.btnViewWidthFit.setIconSize(QtCore.QSize(24, 24))
        self.btnViewWidthFit.setObjectName("btnViewWidthFit")
        self.horizontalLayout_4.addWidget(self.btnViewWidthFit)
        self.btnViewHeightFit = QtWidgets.QPushButton(self.centralWidget)
        self.btnViewHeightFit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/icons/36/window_height.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViewHeightFit.setIcon(icon8)
        self.btnViewHeightFit.setIconSize(QtCore.QSize(24, 24))
        self.btnViewHeightFit.setObjectName("btnViewHeightFit")
        self.horizontalLayout_4.addWidget(self.btnViewHeightFit)
        self.btnViewFitToSize = QtWidgets.QPushButton(self.centralWidget)
        self.btnViewFitToSize.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/icons/36/window_size.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViewFitToSize.setIcon(icon9)
        self.btnViewFitToSize.setIconSize(QtCore.QSize(24, 24))
        self.btnViewFitToSize.setObjectName("btnViewFitToSize")
        self.horizontalLayout_4.addWidget(self.btnViewFitToSize)
        self.btnViewManualZoom = QtWidgets.QPushButton(self.centralWidget)
        self.btnViewManualZoom.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("assets/icons/36/window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViewManualZoom.setIcon(icon10)
        self.btnViewManualZoom.setIconSize(QtCore.QSize(24, 24))
        self.btnViewManualZoom.setObjectName("btnViewManualZoom")
        self.horizontalLayout_4.addWidget(self.btnViewManualZoom)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnPageDoublePage = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageDoublePage.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("assets/icons/36/double_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPageDoublePage.setIcon(icon11)
        self.btnPageDoublePage.setIconSize(QtCore.QSize(24, 24))
        self.btnPageDoublePage.setObjectName("btnPageDoublePage")
        self.horizontalLayout_4.addWidget(self.btnPageDoublePage)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1096, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGo = QtWidgets.QMenu(self.menuBar)
        self.menuGo.setObjectName("menuGo")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setChecked(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Komics = QtWidgets.QAction(MainWindow)
        self.actionAbout_Komics.setObjectName("actionAbout_Komics")
        self.actionNext_Page = QtWidgets.QAction(MainWindow)
        self.actionNext_Page.setObjectName("actionNext_Page")
        self.actionPrevious_Page = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Page.setObjectName("actionPrevious_Page")
        self.actionGoTo_Page = QtWidgets.QAction(MainWindow)
        self.actionGoTo_Page.setObjectName("actionGoTo_Page")
        self.actionEnd_of_Collection = QtWidgets.QAction(MainWindow)
        self.actionEnd_of_Collection.setObjectName("actionEnd_of_Collection")
        self.actionStart_of_Collection = QtWidgets.QAction(MainWindow)
        self.actionStart_of_Collection.setObjectName("actionStart_of_Collection")
        self.actionPrevious_Collection = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Collection.setObjectName("actionPrevious_Collection")
        self.actionNext_Collection = QtWidgets.QAction(MainWindow)
        self.actionNext_Collection.setObjectName("actionNext_Collection")
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionClose_Collection = QtWidgets.QAction(MainWindow)
        self.actionClose_Collection.setObjectName("actionClose_Collection")
        self.actionStart_Slideshow = QtWidgets.QAction(MainWindow)
        self.actionStart_Slideshow.setObjectName("actionStart_Slideshow")
        self.actionFit_to_Width = QtWidgets.QAction(MainWindow)
        self.actionFit_to_Width.setObjectName("actionFit_to_Width")
        self.actionFIt_to_Height = QtWidgets.QAction(MainWindow)
        self.actionFIt_to_Height.setObjectName("actionFIt_to_Height")
        self.actionBest_Fit = QtWidgets.QAction(MainWindow)
        self.actionBest_Fit.setObjectName("actionBest_Fit")
        self.actionZoom_Fit = QtWidgets.QAction(MainWindow)
        self.actionZoom_Fit.setObjectName("actionZoom_Fit")
        self.actionDouble_Page_Layout = QtWidgets.QAction(MainWindow)
        self.actionDouble_Page_Layout.setObjectName("actionDouble_Page_Layout")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionScroll_Forward = QtWidgets.QAction(MainWindow)
        self.actionScroll_Forward.setObjectName("actionScroll_Forward")
        self.actionFull_Screen = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen.setObjectName("actionScroll_Forward")
        self.menuFIle.addAction(self.actionOpen_Directory)
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionClose_Collection)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Komics)
        self.menuGo.addAction(self.actionNext_Page)
        self.menuGo.addAction(self.actionPrevious_Page)
        self.menuGo.addAction(self.actionGoTo_Page)
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.actionStart_of_Collection)
        self.menuGo.addAction(self.actionEnd_of_Collection)
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.actionPrevious_Collection)
        self.menuGo.addAction(self.actionNext_Collection)
        self.menuView.addAction(self.actionFit_to_Width)
        self.menuView.addAction(self.actionFIt_to_Height)
        self.menuView.addAction(self.actionBest_Fit)
        self.menuView.addAction(self.actionZoom_Fit)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDouble_Page_Layout)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionScroll_Forward)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuGo.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Komics"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGo.setTitle(_translate("MainWindow", "Go"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open File or Archive"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout_Komics.setText(_translate("MainWindow", "About Komics"))
        self.actionNext_Page.setText(_translate("MainWindow", "Next Page"))
        self.actionNext_Page.setShortcut(_translate("MainWindow", "Right"))
        self.actionPrevious_Page.setText(_translate("MainWindow", "Previous Page"))
        self.actionPrevious_Page.setShortcut(_translate("MainWindow", "Left"))
        self.actionGoTo_Page.setText(_translate("MainWindow", "GoTo Page"))
        self.actionGoTo_Page.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionEnd_of_Collection.setText(_translate("MainWindow", "End of Collection"))
        self.actionEnd_of_Collection.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.actionStart_of_Collection.setText(_translate("MainWindow", "Start of Collection"))
        self.actionStart_of_Collection.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.actionPrevious_Collection.setText(_translate("MainWindow", "Previous Collection"))
        self.actionPrevious_Collection.setShortcut(_translate("MainWindow", "Ctrl+Shift+Right"))
        self.actionNext_Collection.setText(_translate("MainWindow", "Next Collection"))
        self.actionNext_Collection.setShortcut(_translate("MainWindow", "Ctrl+Shift+Left"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionClose_Collection.setText(_translate("MainWindow", "Close Collection"))
        self.actionClose_Collection.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionStart_Slideshow.setText(_translate("MainWindow", "Start Slideshow"))
        self.actionFit_to_Width.setText(_translate("MainWindow", "Fit to Width"))
        self.actionFIt_to_Height.setText(_translate("MainWindow", "FIt to Height"))
        self.actionBest_Fit.setText(_translate("MainWindow", "Best Fit"))
        self.actionZoom_Fit.setText(_translate("MainWindow", "Zoom Fit"))
        self.actionDouble_Page_Layout.setText(_translate("MainWindow", "Double Page Layout"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "="))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "-"))
        self.actionScroll_Forward.setText(_translate("MainWindow", "Scroll Forward"))
        self.actionScroll_Forward.setShortcut(_translate("MainWindow", "Space"))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.actionFull_Screen.setShortcut(_translate("MainWindow", "F"))

import icons_rc
